### ISSUE TITLE
Mass Edit for Admin users

### ISSUE THREAD

**Issue by barbaralafuente** [OpenDataRepository/data-publisher#33] opened 2015-05-09 00:24 UTC
Give to Admin users the ability to Mass Edit a list of records

**Comment by natestone** [comment] 2015-05-26 14:02
Is this just a request for a permissions change?  I'm not sure when the nature of the issue is since we have mass edit as a function already.

**Comment by barbaralafuente** [comment] 2015-05-29 16:04
Only Super Admin can do Mass Update but Super Admin cannot give permissions for Mass Update to other users.

**Comment by ajpires** [comment] 2015-06-04 17:02
Fixed in commit a179e61

**Closed by ajpires** 2015-06-04 17:02 UTC
Labels: enhancement
