### ISSUE TITLE
List users ADMIN

### ISSUE THREAD

**Issue by barbaralafuente** [OpenDataRepository/data-publisher#17] opened 2015-04-18 15:27 UTC
The list of created users for an ADMIN users only shows 1 user. The ADMIN can create more but they don´t show up in the list.  A SUPER ADMIN can see them is the list of all users

**Comment by natestone** [comment] 2015-04-20 19:25
Confirmed as a bug.  Will investigate a solution.

**Comment by ajpires** [comment] 2015-04-20 21:50
There was a bug here, but it's not quite as described.  It's mostly my fault for not explaining how the user list works right now.

Basically...assume an ADMIN has admin permissions to some arbitrary set of datatypes S = {A, B, D, ...}.  Then the user list only displays users that have view permissions to some subset of the datatypes in S.  This ADMIN user would be unable to "see" some arbitrary user that could only view datatype C, in this example.

This explains what you were seeing before...the newly created users didn't have view permissions for any of the datatypes that the ADMIN user could administrate, so it appeared as if nothing was happening when users were being added.

This should be easier to deal with as a result of commit c7c5292...I've modified the "Add User" page to redirect to the "Manage Permissions" page on two conditions...
1) The username is already in use
2) The new user was successfully added
When on the "Manage Permissions" page, you need to give this user (be they already existing, or brand new) the ability to view one of your datatypes if you want to see them later on in your user list.  Similarly, removing a user's ability to view all of your datatypes will remove them from your user list.

I'm not closing the issue at the moment, because this fix may not be entirely satisfactory...even for one that's not supposed to be permanent.

**Comment by natestone** [comment] 2015-04-24 03:28
Closing - we'll re-open if we need enhancements.

**Closed by natestone** 2015-04-24 03:28 UTC
Labels: bug
