### ISSUE TITLE
Single Select field as Pivot field in graphs 

### ISSUE THREAD

**Issue by barbaralafuente** [OpenDataRepository/data-publisher#88] opened 2015-07-28 22:38 UTC
Allow to use a Single Select field as pivot field in Graph plugin.

**Comment by natestone** [comment] 2015-07-29 17:38
Need to investigate.  I believe this should already be allowed, but there may be a bug.  I'll look into it and reassign the bug or fix depending on the cause.

**Closed** 2019-09-29 22:29 UTC
Labels: bug
