### ISSUE TITLE
Link multiple times per record

### ISSUE THREAD

**Issue by natestone** [OpenDataRepository/data-publisher#7] opened 2015-04-16 04:43 UTC
Related to #6 - need the ability to display different views of the same linked record on a record view.

So, we either need to link it twice or somehow allow the template to display the same linked record with a different view.

Really have no idea how to implement this. Need to discuss.

**Comment by ajpires** [comment] 2015-10-15 19:51
Apparently #82 is a duplicate of this one...but it's phrased slightly better over there, so closing this one.

**Closed by ajpires** 2015-10-15 19:51 UTC
Labels: enhancement
